### ISSUE TITLE
Chromium crash

### ISSUE THREAD

**Issue by Phoenix616** [JayT5/ChromePie#35]
Chromium crashes when this module is installed and enabled.

**Versions:**
Chromium: 62.0.3178.0
ChromePie: 0.6
Xposed: 87 (by PurifyOS, 26-07-17 build)
Android: 7.1.1 Xperia Z1 Compact build/NMF26V (LineageOS 14.1-20170108)

**Comment by JayT5** [comment]
Could you post a logcat of the crash? I've not tried Xposed for Nougat but
I've heard there's problems loading preferences so I would guess it's
something to do with that.

On 5 Aug 2017 7:29 p.m., "Max Lee" <notifications@github.com> wrote:

Chromium crashes when this module is installed and enabled.

*Versions:*
Chromium: 62.0.3178.0
ChromePie: 0.6
Xposed: version 87 (by PurifyOS, 26-07-17 build)
Android: 7.1.1 Xperia Z1 Compact build/NMF26V (LineageOS 14.1-20170108)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JayT5/ChromePie/issues/35>, or mute the thread

**Comment by Phoenix616** [comment]
This should be the right part: https://gist.github.com/69d5853acaa459d94730005763d570ab

**Comment by JayT5** [comment]
Thanks, I'll try and get a release out soon.

On 6 Aug 2017 6:45 p.m., "Max Lee" <notifications@github.com> wrote:

This should be the right part: https://gist.github.com/
69d5853acaa459d94730005763d570ab

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/JayT5/ChromePie/issues/35#issuecomment-320521398>, or mute
the thread

**Comment by JayT5** [comment]
Fixed in e6b294265f8c1ab097baddbf0b840d1fb4339f76
